### ISSUE TITLE
com.apple.InternetSharing.plist On OS X 10.10 (Yosemite)

### ISSUE THREAD

**Issue by benjuang** [champgm/StreetPass#1]
`/System/Library/LaunchDaemons/com.apple.InternetSharing.plist` no longer exists (as far as I can tell) in Yosemite.

There is a `/System/Library/LaunchDaemons/com.apple.NetworkSharing.plist`, but using `launchctl` to load or unload it doesn't appear to start or stop internet sharing.

**Comment by champgm** [comment]
=( 
I don't have yosemite yet, but I will troubleshoot this when I do.

**Comment by RileyMills** [comment]
I'm on 10.10.2 and it seems to have been renamed to 'com.apple.NetworkSharing.plist'.

**Comment by champgm** [comment]
merged Sarkazein's change, thank you for contributing!
